### ISSUE TITLE
GPT2: generate() method does not scale well with batch_size

### ISSUE THREAD

**Issue by dacorvo** [aws-neuron/transformers-neuronx#16] opened 2023-07-04 09:59 UTC
Following the example of `HuggingFaceGenerationModelAdapter`, I have created a `NeuronModelForCausalLM` adapter class for HuggingFace optimum-neuron (see https://github.com/huggingface/optimum-neuron/pull/117).

I compared the inference times for batch sizes of 2 and 16, using either the `GPT2ForSampling` model `sample()` method or transformers `generate()`.
I also added the original pytorch model inference time using transformers `generate()` as a reference.

|                          | neuron sample | neuron generate | pytorch generate |
|--------------------------|---------------|-----------------|------------------|
| 128 tokens batch_size 2  | 0.5 s         | 0.9 s           | 4.6 s            |
| 128 tokens batch_size 16 | 0.8 s         | 2.7 s           | 7 s              |

The neuron model latency using `generate()` is multiplied by 3, where the other two configurations only see less than a x2 increase.

Is this expected ?

**Comment by mrnikwaws** [comment] 2023-07-05 19:57
Closing as duplicate of https://github.com/aws-neuron/transformers-neuronx/issues/16

**Closed by mrnikwaws** 2023-07-05 19:57 UTC
