### ISSUE TITLE
Module metadata  like `License` and `Home-page` are missing

### ISSUE THREAD

**Issue by massi-ang** [aws-neuron/transformers-neuronx#41] opened 2023-09-14 09:51 UTC
After executing `pip install transformers-neuronx --extra-index-url=https://pip.repos.neuron.amazonaws.com`
then `!pip show transformers-neuronx` gives:
```
Name: transformers-neuronx
Version: 0.6.106
Summary: UNKNOWN
Home-page: UNKNOWN
Author: 
Author-email: 
License: UNKNOWN
Location: /home/ubuntu/.local/lib/python3.10/site-packages
Requires: accelerate, torch-neuronx, transformers
Required-by: 
```

**Comment by aws-taylor** [comment] 2023-10-09 17:49
Hello @massi-ang,

 The fix for this is under review and should be fixed in a near-term release.
 
 -Taylor

**Comment by gsnaws** [comment] 2024-01-02 23:31
Hi @massi-ang The issue is resolved.

```
Name: transformers-neuronx
Version: 0.9.387
Summary: Transformers Neuron for Trn1 and Inf2 is a software package that enables PyTorch users to perform large language model (LLM) inference on second-generation Neuron hardware
Home-page: https://github.com/aws-neuron/transformers-neuronx
Author: 
Author-email: 
License: Apache License
Location: /home/ubuntu/aws_neuron_venv_pytorch/lib/python3.8/site-packages
Requires: accelerate, safetensors, torch-neuronx, transformers
Required-by:
```

**Closed** 2024-03-11 15:31 UTC
